#' Render R Markdown
#'
#' Render the input file to a specific output folder. If the Output folder does not exist it will be rendered in the same folder as the input file.
#' 
#' You can also setup the `knit` function in the YAML header of the R Markdown file. See the example below.
#'
#'
#' @param input The input file to be rendered. This can be an R script (.R),
#' an R Markdown document (.Rmd), or a plain markdown document.
#' @param ... Additional arguments passed to the rmarkdown::render function.
#'
#' @return
#'   When \code{run_pandoc = TRUE}, the compiled document is written into
#'   the output file, and the path of the output file is returned. When
#'   \code{run_pandoc = FALSE}, the path of the Markdown output file, with
#'   attributes \code{knit_meta} (the \pkg{knitr} meta data collected from code
#'   chunks) and \code{intermediates} (the intermediate files/directories
#'   generated by \code{render()}).
#' @export
#'
#' @examples
#' \dontrun{
#' library(rmarkdown)
#'
#' # Render the default (first) format defined in the file
#' render("input.Rmd")
#' }
#' 

#' 
knit_LB <- function(input, ...) {
  rmarkdown::render(
    input,
    output_file = if (dir.exists(paste0(dirname(dirname(input)), "/Output"))){paste0(dirname(dirname(input)), "/Output/", xfun::sans_ext(basename(input)), " ", format(Sys.Date(), "%d-%m-%Y"))} else {
      paste0(xfun::sans_ext(input), " ", format(Sys.Date(), "%d-%m-%Y"))},
    envir = globalenv()
  )
}